---
/**:
  ros__parameters:
    joints_map:
      left_front:
        - FL_HipX_joint
        - FL_HipY_joint
        - FL_Knee_joint
        # - FL_Ankle

      right_front:
        - FR_HipX_joint
        - FR_HipY_joint
        - FR_Knee_joint
        # - FR_Ankle

      left_hind:
        - HL_HipX_joint
        - HL_HipY_joint
        - HL_Knee_joint
        # - HL_Ankle

      right_hind:
        - HR_HipX_joint
        - HR_HipY_joint
        - HR_Knee_joint
        # - HR_Ankle
