name: Deploy to Robot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up ROS 2
        run: source /opt/ros/humble/setup.bash

      - name: Build and Deploy
        run: |     
          pip3 install catkin_pkg
          pip3 install empy==3.3.4
          pip3 install lark
          export WORKSPACE_DIR=$HOME/strider_ws
          mkdir -p $WORKSPACE_DIR/src
          rsync -a --exclude=$WORKSPACE_DIR --exclude=.git ./ $WORKSPACE_DIR/src/
          unset PYTHONPATH
          export PATH="/usr/bin:/bin:$PATH"
          cd $WORKSPACE_DIR
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y
          colcon build --symlink-install

